### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by SHXRKIEgg** [yungnickyoung/YUNGs-Better-Dungeons#12]
Testing with Better Minecraft Fabric, it crashes but doesn't give me a Crash report but reports it in the log.
https://pastebin.com/Nc7MKd1L

**Comment by yungnickyoung** [comment]
This `Accessing PalettedContainer from multiple threads` bug is something that started popping up in 1.17. Seems to be some obscure side effect to one of the changes Mojang made. I thought I had implemented a workaround, but looks like I missed a few spots. I'll upload a fixed version soon

**Comment by yungnickyoung** [comment]
Should be fixed in v1.0.1. Let me know if it works!

**Comment by itsdinkd** [comment]
Could this be caused by Charm?

![image](https://user-images.githubusercontent.com/35115304/132930337-e472152a-912b-4dd0-9492-fe582e848f0b.png)

**Comment by SHXRKIEgg** [comment]
> Should be fixed in v1.0.1. Let me know if it works!

Seems to be fixed thanks!
