### ISSUE TITLE
[Compatibility] Charm Dungeon / When Dungeons Arise

### ISSUE THREAD

**Issue by itsdinkd** [yungnickyoung/YUNGs-Better-Dungeons#13]
Would Better Dungeons be compatible with third party dungeon mods such as When Dungeons Arise? Or even Charm Dungeons as Charm replaces vanilla? 

[1.17.1 / Fabric]

**Comment by itsdinkd** [comment]
Also, is this compatible with 1.18 heights? minY = -60?

**Comment by yungnickyoung** [comment]
Should be compatible with both, yes. And yeah, you should be able to set negative y coordinates.

Please ask questions in the Discord btw, as this is intended for bug reports, not questions

[discord.gg/rns3beq](https://discord.gg/rns3beq)
