### ISSUE TITLE
Possible issue with world gen

### ISSUE THREAD

**Issue by ShootToKillSTK** [yungnickyoung/YUNGs-Better-Dungeons#16]
Playing on 1.16.5 Forge 2.0, BetterDungeons-1.16.4-1.2.jar With other mods, not really sure if issue with this mod or something else but crash logs show stuff with this mod

Crashes on loading/generating a world, sometimes gets to '0%' loaded and freezes, then crash other times doesn't even get there

Here's Github of .latest and Crash log:
https://gist.github.com/ShootToKillSTK/b30b1096bc03fbbe6c917aa1e0a7e836

**Comment by yungnickyoung** [comment]
Exception thrown is `java.lang.NoClassDefFoundError: net/silentchaos512/scalinghealth/utils/config/SHDifficulty`. I would send this to the author of the Scaling Health mod.
