### ISSUE TITLE
Dungeon Structures spawning in The End void

### ISSUE THREAD

**Issue by Kizwiz** [yungnickyoung/YUNGs-Better-Dungeons#2]
Loaded up a fresh game, went to The End and there are a ton of dungeon structures just floating around in the end void

**Comment by yungnickyoung** [comment]
Can you try to figure out which of your other mods causes this to happen?

**Comment by Hir0shiyt** [comment]
The last log would help a little bit to see what the problem is, right?

**Comment by yungnickyoung** [comment]
It doesn't hurt to post it, but I'm not sure it will help. There have been similar issues with my other mods in the past that were usually due to another mod performing some improper feature registration.

**Comment by Kizwiz** [comment]
I will remove my mods 1 by 1 to find the offending mod tomorrow

**Comment by yungnickyoung** [comment]
I you're using Better Portals, make sure you're on the latest version. There was an issue it had that could cause this.

Also, pro tip - try removing half of your mods instead. If the bug remains, then you know that one of the mods you still have enabled is causing the problem. Repeat the process, removing 50% of the remaining mods at a time, until you can determine which mod is causing it. This process will save way more time than removing one mod at a time.

**Comment by Kizwiz** [comment]
I think its multiple mods causing the issues. I've managed to find one doing it, its:
https://www.curseforge.com/minecraft/mc-mods/kobolds

**Comment by Kizwiz** [comment]
Found another mod causing the issue:
https://www.curseforge.com/minecraft/mc-mods/apotheosis

I've removed both Apotheosis and Kobolds and as far as I can see the issue is resolved

**Comment by Fizzie617** [comment]
![2021-08-03_17 46 37](https://user-images.githubusercontent.com/85355884/128095920-f5bbab00-1ed7-45ce-bec1-26a18703e653.png) Found some in Atum 2 as well without kobolds installed. otherwise I haven't seen them spawn in any other modded dimension.

**Comment by yungnickyoung** [comment]
So far, this has been reported to happen with Kobolds, Stalwart Dungeons, and Apotheosis if you have the Deadly module enabled. If you have any of these mods, dungeons will spawn in every dimension.

**Comment by yungnickyoung** [comment]
Everyone - v1.1 introduces dimension whitelists and biome blacklists for each dungeon. Give it a try and see if it fixes your issues, and let me know if it works!

**Comment by Jusey1** [comment]
> 
> 
> I think its multiple mods causing the issues. I've managed to find one doing it, its:
> https://www.curseforge.com/minecraft/mc-mods/kobolds

![Untitled](https://user-images.githubusercontent.com/61861078/128622125-bb2f7ed0-a897-4ddf-a280-23347a7d6378.png)

I know that YUNG made a fix on his end in 1.1 but I decided to fix the bug on my end as well. So 1.4.2 version of Kobolds will no longer have this conflict for any future dungeon-related mods (or ones that are already out as well).

**Comment by Fizzie617** [comment]
Sorry for my late reply but yea I've been running the latest version of both of your guys mods and have had no problems since 👍
