### ISSUE TITLE
Weird generation issues

### ISSUE THREAD

**Issue by Mr-Syntax** [yungnickyoung/YUNGs-Better-Dungeons#22]
It seems when i go to a spider dungeon in this pack https://www.curseforge.com/minecraft/modpacks/chosencraft
that the client tick will increase by 5 ms 

can you please look into this issue??

also sometimes the crypt will spawn in the middle of the ocean?

**Comment by Mr-Syntax** [comment]
ahh actually its in the BYG:tropical_isle biome think thats the problem

**Comment by yungnickyoung** [comment]
Seems the issue was solved. The catacombs will not spawn in biomes properly marked as oceans, although they can still spawn in smaller bits of water - see #10
