### ISSUE TITLE
1.18 version crashes on Startup!!!

### ISSUE THREAD

**Issue by ModernGamingWorld** [yungnickyoung/YUNGs-Better-Dungeons#28]
As soon as I installed the mod and went to launch my custom mod pack, the Modpack crashed with errors within the log file

[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Dungeons/files/8128547/latest.log)

**Comment by ModernGamingWorld** [comment]
I saw something about Repurposed Structures

**Comment by yungnickyoung** [comment]
Hey, working on a fix now!

**Comment by yungnickyoung** [comment]
Please try v1.0.1, available here: https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons/files/3659567
