### ISSUE TITLE
[SUGGESTION] Config option to blacklist biomes

### ISSUE THREAD

**Issue by CriticAlias** [yungnickyoung/YUNGs-Better-Dungeons#3]
Hey, it would be great if a config option were added to blacklist dungeons from spawning in certain biomes. I'm mainly suggesting this because certain biomes with lots of water can have dungeon entrances spawn in them, at least for the spider caves from what I've found. Additionally, or otherwise, it would be great if the entrances would avoid spawning in water. Thanks :)

**Comment by yungnickyoung** [comment]
Added in v1.1!
