### ISSUE TITLE
"Experimental settings" warning on clean world with nothing else installed

### ISSUE THREAD

**Issue by ccrowles** [yungnickyoung/YUNGs-Better-Dungeons#34]
Exactly the same as [the issue I submitted for Better Mineshafts](https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/issues/81): I get the experimental settings warning on a new instance in a new world with only this mod and its api installed.

Minecraft version: 1.18.2
Forge version: 40.1.16

Logfile: 
[latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/files/8645156/latest.log)

PolyMC output: [here](https://0x0.st/omom.txt)

**Comment by yungnickyoung** [comment]
Addressed in Better Strongholds issue.
