### ISSUE TITLE
Incorrect Achievement Text for Dungeons

### ISSUE THREAD

**Issue by ninjakitty844** [yungnickyoung/YUNGs-Better-Dungeons#36]
This might be a one off, i havent found enough other dungeons to tell, but when I enter the zombie dungeon this is what prints in chat:

[Player] just made the advancement betterdungeons.advancements.zombie_dungeon.title
_betterdungeons.advancements.zombiedungeon.description

**Comment by yungnickyoung** [comment]
Sounds like you're playing with the mod only on the server, and not on the client. You need to either install the mod on your client, or install this [resource pack](https://www.curseforge.com/minecraft/texture-packs/yungs-better-dungeons-resource-pack) on the client.

Once the 1.19 version is out, the resource pack should no longer be required for clients to see the English translation
