### ISSUE TITLE
bad catacomb + nest generation in big cave

### ISSUE THREAD

**Issue by Wedge1453** [yungnickyoung/YUNGs-Better-Dungeons#38]
![2022-06-11_19 03 38](https://user-images.githubusercontent.com/76813383/173201126-1fc5993c-32fb-476e-b794-77cce38414b5.png)

**Comment by Jukabofy** [comment]
is a minecraft thing, if you want to low the spawnrate of this structures you have to use datapacks
tha one is just a coincidence, like exposed mineshafts in a big cave

**Comment by yungnickyoung** [comment]
The open air behavior for both of these dungeons is intended because they were first designed for 1.16, when caves were much less massive. I may consider fixing up this behavior to be more compatible with massive caves in the future, but it's a low priority item. Thanks for reporting though!
