### ISSUE TITLE
Pillager Fortress too many mob

### ISSUE THREAD

**Issue by SeRa67** [yungnickyoung/YUNGs-Better-Dungeons#39]
The pillagers fortress just spawn to much mob and cause lot of lag, i'm not complaining about it being to hard but when i go to it my fps just drop from 120 down to 10, and also idk if it is a feature or not but when you have the bad omen effect it start a raid, and spawning even more pillagers.
Some screenshot to show you
![2022-06-20_19 25 20](https://user-images.githubusercontent.com/107880928/174654324-6af91505-7ae0-488d-8b8e-b41993e2ea1a.png)
![2022-06-20_19 24 52](https://user-images.githubusercontent.com/107880928/174654354-f5a8918d-c80b-4bed-bacd-ff44b5bf1a38.png)
![2022-06-20_19 24 36](https://user-images.githubusercontent.com/107880928/174654393-e01199ed-f200-4e91-ae47-d1695f980a12.png)

**Comment by Jukabofy** [comment]
that structure doesn't exists in this mod

**Comment by SeRa67** [comment]
Yep sry it was idas

**Comment by Jukabofy** [comment]
Don't worry, is somthing that could happen anytime
Btw, if I'm not wrong the structure is from https://www.curseforge.com/minecraft/mc-mods/idas

**Comment by yungnickyoung** [comment]
Indeed, this is from IDAS. Closing since it's another mod's
