### ISSUE TITLE
Random Server Crash

### ISSUE THREAD

**Issue by ahmadelafify** [yungnickyoung/YUNGs-Better-Dungeons#44]
Hello! My Better MC 1.19 server has been crashing due to sumn in Yung's Mobs. 

### Error:
Accessing LegacyRandomSource from multiple threads

### Temp Solution:
I have a repeating command block to kill pillagers which has made the crashing more uncommon. 

### Here is a crash report:
https://mclo.gs/OIsa5dP

**Comment by ahmadelafify** [comment]
Crash occurred again:

Crash report:
https://mclo.gs/RTtQiqz

**Comment by yungnickyoung** [comment]
This appears to be this issue from Savage and Ravage: [https://github.com/team-abnormals/savage-and-ravage/issues/119](https://github.com/team-abnormals/savage-and-ravage/issues/119)

**Comment by ahmadelafify** [comment]
Ahh, I see thank you for the clarification!
