### ISSUE TITLE
Config to completely remove dungeon types?

### ISSUE THREAD

**Issue by sisby-folk** [yungnickyoung/YUNGs-Better-Dungeons#45]
I'd like to remove spider dungeons, and I've tried to set min and max to all kinds of weird values so they don't spawn, but i'm unfortunately still finding them :joy:

**Comment by yungnickyoung** [comment]
What version are you on? In older versions, you can disable each dungeon type via the config. In 1.18+, you'll need to use a data pack to override the dungeon's list of possible biomes to spawn in.

**Comment by sisby-folk** [comment]
1.18+ - is there an example of a data pack?

**Comment by yungnickyoung** [comment]
I don't have an example on hand, but it would be a very simple data pack - just create a file called `has_spider_dungeon.json` (or just `spider_dungeon.json` if on 1.19) in `data/betterdungeons/tags/worldgen/biome/has_structure/` that looks like the following:

```json
{
  "replace": true,
  "values": [
  ]
}
```

This will override the list of biomes Spider Dungeons can spawn in with an empty list, meaning it will not spawn in any biomes.

**Comment by sisby-folk** [comment]
thanks! feel free to close.

**Comment by ghost** [comment]
Can this be done when just installing the mod via the .jar file? 
I tried creating a file in `~/.minecraft/data/betterdungeons/tags/worldgen/biome/has_structure/`, but it didn't seem to work.
