### ISSUE TITLE
[1.19.2] Missing option for vanilla dungeons

### ISSUE THREAD

**Issue by Aleon4201** [yungnickyoung/YUNGs-Better-Dungeons#48]
In 1.18.2, there was an option if this mod remove vanilla small dungeons or not in General settings block.
```
		# Whether or not vanilla dungeons should be prevented from spawning in the world.
		# It is recommended to disable these, since the Small Dungeons are very similar in design.
		# Default: true
		#
		"Remove Vanilla Dungeons" = false
```
But now, in 1.19.2, there's not.
Maybe this mod removes all small vanilla dungeons forcely.
Or doesn't it remove?

**Comment by Xonazeth** [comment]
This setting is still in fact not in the mod config and the vanilla dungeons do still spawn and they spawn more than the better dungeons do. I hope this gets fixed!

**Comment by yungnickyoung** [comment]
Apologies for such a late bump.

Forge added a thing called biome modifiers in 1.19 for removing vanilla features, so I removed the config option from the Forge version of the mod. It should still be there in the Fabric version. If you want the vanilla small dungeons to still spawn on Forge, you can make a datapack that overrides this file: https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/blob/1.20/Common/src/main/resources/data/betterdungeons/forge/biome_modifier/vanilla_dungeon_removal.json

As for vanilla dungeons still spawning - they will in fact still spawn in biomes where my other dungeons do not, which should really only happen in some rare modded biomes. But yeah in those rare biomes you will find exclusively vanilla dungeons and none of my small dungeons.

If you have any more questions feel free to ask in the [discord](https://discord.gg/yung)!
