### ISSUE TITLE
"minecraft:deep_warm_ocean_biome" not blacklisted for dungeon spawn

### ISSUE THREAD

**Issue by pesesta** [yungnickyoung/YUNGs-Better-Dungeons#5]
Minor issue affecting Better Dungeons-1.6.4-1.1:

The default config does not blacklist the "minecraft:deep_warm_ocean biome" for dungeon spawns. I've seen small dungeons and spider dungeons generate freely up from the ocean floor to the surface.

This is easily fixed on the user side by amending the config of course, but might be something to change in the initial one installed.

(P.S. great mod as ever though)

**Comment by yungnickyoung** [comment]
Great catch! Fixed in v1.2 :)
