### ISSUE TITLE
Spider Nest ignoring Magnum Torch

### ISSUE THREAD

**Issue by AlisonHuang777** [yungnickyoung/YUNGs-Better-Dungeons#56]
Cave Spiders still spawns in the vicinity of Magnum Torch (https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge). No spawner near.

**Comment by yungnickyoung** [comment]
Is magnum torch intended to stop structure mob spawns? Mobs that spawn as designated by a structure's json work differently than normal environmental mob spawns. I wouldn't be surprised if magnum torch is intended to only stop natural environmental spawns, and not structural ones.

**Comment by AlisonHuang777** [comment]
Yes, Magnum Torch only prevents natural mob spawning, according to the mod's curseforge page.
