### ISSUE TITLE
(Suggestion) Config option to use vanilla loot tables.

### ISSUE THREAD

**Issue by penguin-glitch** [yungnickyoung/YUNGs-Better-Dungeons#58]
As it stands most of the chests in this mod's dungeons will not have loot from other mods that add to the vanilla loottables. Rather than adding each mod's items individually, it would be convenient if there was a config option to force all chests generated by this mod to use vanilla loot tables (this may cause some dungeons to have loot that doesnt make sense, however)

**Comment by yungnickyoung** [comment]
Well, the improved small dungeons still use vanilla loot tables to maintain compatibility with other mods that may modify vanilla dungeon loot tables
