### ISSUE TITLE
[Question] compatibility with Quark's big dungeons.

### ISSUE THREAD

**Issue by Wedge1453** [yungnickyoung/YUNGs-Better-Dungeons#6]
does the mod replace all vanilla dungeons and leave nothing to quark's big dungeons?

**Comment by WindFox** [comment]
I'm gonna say it's fine. I have this mod and Quark in a pack and I just finished up a Quark dungeon.

**Comment by yungnickyoung** [comment]
Quark dungeons will work just fine.
