### ISSUE TITLE
(Potential bug) Strange world generation issue with the Catacombs

### ISSUE THREAD

**Issue by LessThanBenji** [yungnickyoung/YUNGs-Better-Dungeons#60]
As seen in the screenshots below, what Catacombs decide to do when they're generating in the air is quite... interesting. Obviously the stilts/support pillars are intentional, but I'm not sure they're supposed to do *that* -- they seem a bit long. Don't know what could be done to combat this, as I suppose it'd look weirder if those parts of the Catacombs were floating instead... maybe less/a lower density of pillars? Brilliant mod otherwise, huge kudos to you for your insane work!

![2024-03-21_15 01 37](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/assets/63028933/28be5ab5-dd6f-4516-b596-2fb1411847d9)
![2024-03-21_15 01 43](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/assets/63028933/c0602e89-9b6d-49cb-a1a5-a239b0b0bc97)
![2024-03-21_15 02 18](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/assets/63028933/7e2f28da-b38a-47bd-af90-7fbce2dbd3a7)
![2024-03-21_15 02 35](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/assets/63028933/228e2509-3b97-4106-967a-183f8cec776f)
![2024-03-21_15 01 55](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/assets/63028933/98f48fec-a811-4ed0-a0e9-76254c1bbdb3)

**Comment by yungnickyoung** [comment]
Hey, glad you like the mod! This is just kinda the result of the initial design of the dungeons + the newer giant 1.18 caves. I know it's not ideal, but at this point this mod is pretty finalized so I'm going to be marking this issue as wontfix.
