### ISSUE TITLE
(Bug) YUNG's better dungeons make my game crash

### ISSUE THREAD

**Issue by DARKLOL680** [yungnickyoung/YUNGs-Better-Dungeons#61]
[latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/files/14736443/latest.log)
whenever i opened my world with this mod the game crashed almost immediatly

**Comment by yungnickyoung** [comment]
This is unrelated to my mod, and looks to be an issue with your shaders. It looks like you might have a mod conflicting with Iris. I also recommend upgrading your graphics drivers.
