### ISSUE TITLE
[1.21.1] Crash on rare combination of events

### ISSUE THREAD

**Issue by pietro-lopes** [yungnickyoung/YUNGs-Better-Dungeons#70]
When Skeleton Dungeon and Small Dungeon overlaps just at the exact place where a Jukebox (Skeleton Dungeon side) and a Red Banner (Small Dungeon side) overlaps, it causes a crash.

Seed: `-7806792279352025342`
place to crash:
`tp @s -1232 120 -3648`

Crash log: https://mclo.gs/qP8kOcM

This can be fixed setting nbt here to `null` as this is Air anyway
https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/blob/a86c1a36b61480b5ee2862eb3a477f001856e9a1/Common/src/main/java/com/yungnickyoung/minecraft/betterdungeons/world/processor/small_dungeon/SmallDungeonBannerProcessor.java#L107

https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/blob/a86c1a36b61480b5ee2862eb3a477f001856e9a1/Common/src/main/java/com/yungnickyoung/minecraft/betterdungeons/world/processor/small_dungeon/SmallDungeonBannerProcessor.java#L112

How it generates after the fix:
![image](https://github.com/user-attachments/assets/1aabcd3a-a38d-4e83-b4e5-5b4417cb1f30)

**Comment by yungnickyoung** [comment]
Fixed in v5.1.4.
