### ISSUE TITLE
Quark's World Feature "Crevices" destroy the Better Dungeons

### ISSUE THREAD

**Issue by szunakabeats** [yungnickyoung/YUNGs-Better-Dungeons#9]
![2021-08-14_22 25 22](https://user-images.githubusercontent.com/88375166/129459394-0aa8f7b6-3f1b-4fea-8276-655a719ebeae.png)
![2021-08-14_22 25 31](https://user-images.githubusercontent.com/88375166/129459395-5a1c0faf-9bdb-4cd1-8d14-2c7b4b677f4d.png)

**Comment by yungnickyoung** [comment]
Unfortunately this is unavoidable. I recommend disabling Quark Crevices and Mega Caves, as they will destroy anything.
